---
title: "Mini Project 3"
author: Natalia Iannucci and Hana Hirano
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE}
library(tidyverse)
library(macleish)
library(leaflet)
library(sf)

macleish_trails <- macleish_layers %>%
  pluck("trails")
trails_leaflet <- leaflet() %>%
  addTiles() %>%
  addPolylines(data = macleish_trails)#, color = ~pal(macleish_trails$name)) 
  
trails_leaflet
```

```{r}
elevation <- macleish_layers %>%
  pluck("contours_3m") %>%
  st_transform(4326)
```

```{r message=FALSE}
elevation_trails <- st_intersection(
  macleish_trails,
  elevation
) 

```

```{r}
grouped <- elevation_trails %>%
  filter(name %in% c("entry trail", "Western Loop", "Eastern Loop", "Vernal Pool Loop", "Porcupine Trail", "Easy Out")) %>%
  group_by(name) %>%
  summarize(elevation_ft = sum(ELEV_FT), distance = sum(SHAPE_LEN))

grouped <- grouped %>% 
  mutate("Distance_miles" = distance / 5280) %>%
  mutate("Difficulty" = sqrt(elevation_ft * 2 * Distance_miles))
```

```{r message=FALSE}
pal <- colorNumeric(c("Red", "Red", "Red", "Green", "Yellow", "Yellow"))

difficulty_map <- leaflet() %>%
  addTiles() %>%
  addPolylines(data = macleish_trails, color = ~pal(c(1, 4, 6, 2, 3, 5)))

difficulty_map
```

```{r}
a  <- elevation_trails %>%
  filter(name == "Western Loop")
```

SQRT(Elevation Gain(in feet) x 2 x distance (in miles))
- less than 50 : Easiest (1.5 miles per hour)
- 50 ~ 100 : Moderate (1.4 miles per hour)
- 100 ~ 150 : Moderately Strenuous (1.3 mph)
- 150 ~ 200 : Strenuous (1.2 mph)
- 200 ~ : Very Strenuous (1.2 mph)